---
- hosts: all
  become: true
  tasks:
   - name: remove nginx on ubuntu host
     apt:
      name: nginx
      state: absent

   - name: Install nginx on Ubuntu
     apt:
       name:
         - nginx
       state: present
     when:
       - (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "22")
       #- (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "20")

   - name: Install nginx on Centos
     yum:
       name:
         - nginx
       state: present
     when:
       - (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "8")
       #- (ansible_facts['distribution'] == "Centos" and ansible_facts['distribution_major_version'] == "8")

   - name: starting nginx service
     service:
         name: nginx
         state: started
